<?php


namespace app\controller;
use think\Controller;

class Movie extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        return $this->video();
    }

    public function video()
    {
        try {
            return $this->view->fetch('movie/video');
        } catch (\Exception $e) {
        }
    }
}