<?php


namespace app\controller;
use app\model\User;
use app\model\Userinfo;
use think\Controller;


class Register extends Controller
{
    private $ubasic_info = [
        'username' => '',
        'password' =>'',
        'gender' =>'',
        'QQ' =>''
    ];
    private $regFlag = false;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        /*$message = $this->regFlag ? 'success' : 'failure';
        return $message;*/
    }

    public function recvForm()
    {
        $n1 = $n2 = $n3 = $n4 = 0;
        $ubinfo = $this->request->post();
        if (!empty($ubinfo))
        {
            if (!empty($ubinfo['name'])){
                $this->ubasic_info['username'] = $ubinfo['name'];
                $n1 = 1;
            }
            if (!empty($ubinfo['pwd'])){
                $this->ubasic_info['password'] = base64_encode($ubinfo['pwd']);
                $n2 = 1;
            }
            if (!empty($ubinfo['sex'])){
                $this->ubasic_info['gender'] = $ubinfo['sex'];
                $n3 = 1;
            }
            if (!empty($ubinfo['QQ'])){
                $this->ubasic_info['QQ'] = $ubinfo['QQ'];
                $n4 = 1;
            }
            if($n1&&$n2&&$n3&&$n4){
                $this->regFlag = true;
            }
        }
        if ($this->regFlag) //&& $this->regValid并且参数合法,再保存到数据库中去
        {
            $root = ROOT_PATH;
            $this->regUser();
            echo <<<EOF
<script>alert('注册成功');window.location.href="{$root}/public/login";</script>
EOF;
        }
        else{
            return json(['tip' => '注册数据非法-或信息不完善']);
        }
    }

    public function regUser()
    {
        $user = new User();
        $user -> save($this->ubasic_info);
        $u_info = new Userinfo();
        $condition = [
            'username' => $this->ubasic_info['username'],
            'userLevel' => 1,
            'userBhard' => 0,
            'userExpBar' => 0,
            'userfollow' => 0,
            'userfans' => 0,
            'userdynamic' => 0,
            'ufacePath' => 'm03.jpg'
        ];
        $u_info -> save($condition);
    }

    public function modifyUser()
    {
        //$user = new User();
    }
}